{"name": "test_three[5-7-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 9\n +  where 12 = add(5, 7)", "trace": "self = <Work.test_work2.TestA object at 0x10de9da20>, module = None\nclassA_end = None, a = 5, b = 7, expected = 9\n\n    @pytest.mark.parametrize(\"a,b,expected\", [(5, 7, 9)])\n    def test_three(self, module, classA_end, a, b, expected):\n        logging.info(\"This is test_three!!!\")\n>       assert add(a, b) == expected\nE       assert 12 == 9\nE        +  where 12 = add(5, 7)\n\ntest_work2.py:28: AssertionError"}, "attachments": [{"name": "log", "source": "cf8d45b0-b440-4523-b6da-ce9a3d1f8fdf-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "a1349fe2-c5dc-4ae8-af84-277598ce7d18-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "5"}, {"name": "b", "value": "7"}, {"name": "expected", "value": "9"}], "start": 1573546636320, "stop": 1573546636320, "uuid": "ee439365-8b99-49e6-903d-b729fce9365e", "historyId": "67788ebee6ba081243870e930b32a23f", "testCaseId": "654440bd0d0559254558d9c8c3f84b7b", "fullName": "test_work2.TestA#test_three", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestA"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}