{"name": "test_five", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 8\n +  where 10 = add(5, 5)", "trace": "self = <Work.test_work2.TestB object at 0x10dea3fd0>, module = None\nclassB_start = None\n\n    def test_five(self, module, classB_start):\n        logging.info(\"This is test_five!!!\")\n>       assert add(5, 5) == 8\nE       assert 10 == 8\nE        +  where 10 = add(5, 5)\n\ntest_work2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "9790a062-7ce9-4bea-9fac-c62b38846f12-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "11b2fd0b-cf46-4ebf-96f8-f7c3c8097ec3-attachment.txt", "type": "text/plain"}], "start": 1573546636364, "stop": 1573546636365, "uuid": "0f23da23-515c-4d96-85f5-af7fecca37a6", "historyId": "f404a0e497806cca9f97bd6ab5a0dc79", "testCaseId": "1c304be36e911a2dc5dc41fae2b8e66a", "fullName": "test_work2.TestB#test_five", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}