{"name": "test_six[10-2-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 12 == 5\n +  where 12 = add(10, 2)", "trace": "self = <Work.test_work2.TestB object at 0x10df0af98>, module = None\nclassB_start = None, a = 10, b = 2, expected = 5\n\n    @pytest.mark.parametrize(\"a,b,expected\", json.load(open(\"calc.json\")))\n    def test_six(self, module, classB_start, a, b, expected):\n        # a = json.load(open(\"calc.json\"))\n        # print(a[\"login\"])\n        logging.info(\"This is test_six!!!\")\n>       assert add(a, b) == expected\nE       assert 12 == 5\nE        +  where 12 = add(10, 2)\n\ntest_work2.py:45: AssertionError"}, "attachments": [{"name": "log", "source": "dd3e9588-5a2a-406a-98a8-1acb1880a673-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "294c729b-5a73-4c0e-82f3-6fae95feab52-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "10"}, {"name": "b", "value": "2"}, {"name": "expected", "value": "5"}], "start": 1573546636386, "stop": 1573546636386, "uuid": "ad528915-731b-43d2-9ad5-9a6f9785bf76", "historyId": "1a5de33974d0bd15ec4df2622a6e6adf", "testCaseId": "4f6de44d5dec1d8b69075d2b48ad4434", "fullName": "test_work2.TestB#test_six", "labels": [{"name": "suite", "value": "test_work2"}, {"name": "subSuite", "value": "TestB"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work2"}]}