{"name": "test_nine[8-6-2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 == 2\n +  where 14 = add(8, 6)", "trace": "self = <Work.test_work.TestC object at 0x10df2f8d0>, a = 8, b = 6, expected = 2\n\n    @pytest.mark.run(order=2)\n    # @pytest.mark.run('second')\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 14 == 2\nE        +  where 14 = add(8, 6)\n\ntest_work.py:81: AssertionError"}, "attachments": [{"name": "log", "source": "e9ac3dd2-bae7-4e7a-98f1-59a3a5c7c43a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "85105caa-c83f-488d-bf64-b4632dd6040c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "8"}, {"name": "b", "value": "6"}, {"name": "expected", "value": "2"}], "start": 1573546636496, "stop": 1573546636496, "uuid": "46be704b-4f2b-4aa4-a1ff-ac8e22eb261e", "historyId": "1421ced879ca407d6d0fe92ae584a01a", "testCaseId": "94eee2a481c08a178297ee94c3c1d95a", "fullName": "test_work.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}