{"name": "test_nine[3-3-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 9\n +  where 6 = add(3, 3)", "trace": "self = <Work.test_work.TestC object at 0x10df4e710>, a = 3, b = 3, expected = 9\n\n    @pytest.mark.run(order=2)\n    # @pytest.mark.run('second')\n    @pytest.mark.parametrize(\"a,b,expected\", yaml.load(open(\"calc.yaml\")))\n    def test_nine(self, a, b, expected):\n        logging.info(\"This is test_nine!!!\")\n>       assert add(a, b) == expected\nE       assert 6 == 9\nE        +  where 6 = add(3, 3)\n\ntest_work.py:81: AssertionError"}, "attachments": [{"name": "log", "source": "04132994-4156-4bf9-a48b-bcecadd79224-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ed9d2330-85d7-45a3-a68f-2952f0273468-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "3"}, {"name": "b", "value": "3"}, {"name": "expected", "value": "9"}], "start": 1573546636486, "stop": 1573546636486, "uuid": "d0d6958c-6e18-45cd-9f50-e13b5baa3eeb", "historyId": "1e47cfe1eb37baeaa0c789e5434618f6", "testCaseId": "94eee2a481c08a178297ee94c3c1d95a", "fullName": "test_work.TestC#test_nine", "labels": [{"name": "suite", "value": "test_work"}, {"name": "subSuite", "value": "TestC"}, {"name": "host", "value": "ZTL.local"}, {"name": "thread", "value": "3894-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_work"}]}